project:
  type: book
  output-dir: docs

number-sections: true

book:
  title: "Brandutsatta konstruktioner"
  author: "Joakim Sandström, LTU"
  
  repo-url: https://github.com/LTU-fire/sfd-book/
  repo-subdir: chapters
  repo-branch: main
  repo-actions: [issue]
  url: https://LTU-fire.github.io/sfd-book/
  sidebar:
    logo: figures/dragonLogo.png
    search: true
  sharing: [twitter, facebook, linkedin]

  chapters:
    - index.qmd
    - chapters/01_loads.qmd
    - chapters/07_fire.qmd
    - chapters/02_steel.qmd
    - chapters/03_timber.qmd
    - chapters/04_concrete.qmd
    - chapters/05_design.qmd
    - chapters/06_pbd.qmd

  
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    fontfamily: Garamond
