project:
  type: book

number-sections: true

book:
  title: "Brandteknisk dimensionering av bärande konstruktioner"
  author: "Joakim Sandström, LTU"

  chapters:
    - index.qmd
    - chapters/01_loads.qmd
    - chapters/02_steel.qmd
    - chapters/03_timber.qmd
    - chapters/04_concrete.qmd
    - chapters/05_design.qmd
    - chapters/06_pbd.qmd

  
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt